---

- ufw:
    state: enabled
    policy: deny
  become: true
  tags: nginx

- ufw:
    rule: limit
    port: ssh
    proto: tcp
  become: true
  tags: nginx

- ufw:
    rule: allow
    port: 22
  become: true
  tags: nginx

- ufw:
    rule: allow
    port: 80
  become: true
  tags: nginx

- ufw:
    rule: allow
    port: 443
  become: true
  tags: nginx

- name: Remove root dir
  lineinfile:
    path: /etc/nginx/nginx.conf
    state: absent
    regexp: 'root.+/usr/share/nginx/html'
  become: true
  tags: ngnix

- name: insert upstream
  blockinfile:
    path: /etc/nginx/nginx.conf
    marker: "# {mark} ANSIBLE MANAGED BLOCK upstream"
    insertafter: "http {"

    content: "    include blockips.conf;\n      upstream myapp {\n        server 127.0.0.1:8888;\n    }"
  become: true
  tags: ngnix

- name: insert proxy settings
  blockinfile:
    path: /etc/nginx/nginx.conf
    marker: "# {mark} ANSIBLE MANAGED BLOCK proxy settings"
    insertafter: "^[^#]*location */ *{"
    content: |
        proxy_pass http://myapp;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
  become: true
  tags: nginx

- name: Copy blocked ip address file
  copy:
    src: blockips.conf
    dest: /etc/nginx/blockips.conf
    owner: root
    group: root
    mode: 0644
  become: true
  tags: nginx

- name: Test if new config is ok
  command: "/usr/sbin/nginx -t"
  changed_when: False
  become: true
  tags:
    - nginx

- name: Work a round nginx bug
  shell: 'ps -ef|grep nginx|grep master|grep -v grep|tr -s " " | cut -d " " -f2 >/run/nginx.pid'
  become: yes
  become_user: root
  tags:
    - nginx

      #prøv service nginx status     på hjernen
      #Må komfe
      #tilnød ps -aux | grep nginx
      # service fungerer rett og slett ikke. Får bruke
- name: Make sure web server is still running. Service module does not work with older nginx.
  #  service: name=nginx state=started enabled=yes
  # command: "service nginx start" #virker ikke
  become: yes
  command: "/usr/sbin/nginx -s reload"
  become_user: root
  tags:
    - nginx
