---
- hosts: cloudatcost
  roles:
    - yum
    - git
    - {
        role: perlbrew,
        perlbrew_user: root,
        perlbrew_root: /opt/perlbrew,
        use_profile: true,
        tags: [ 'perlbrew' ]
      }
