---
- hosts: cloudatcost
  roles:
    - yum
    - {
        role: nginx,
        tags: [ 'nginx' ]
      }
    - git
    - email
    - {
        role: perlbrew,
        perlbrew_user: stein,
        use_profile: true,
        tags: [ 'perlbrew','perl' ]
      }
    - {
        role: nginx-security,
        tags: ['mojo','nginx']
      }