---
- hosts: cloudatcost
  roles:
    - yum
    - {role:
        role: nginx,
        tags: [ 'nginx' ]
      }
    - git
    - {
        role: perlbrew,
        perlbrew_user: stein,
        use_profile: true,
        tags: [ 'perlbrew','perl' ]
      }
    - end
