yumpackages:
  - tmux
  - perl
  - cpan
  - gcc
  - git
  - nginx
  - cpanminus
  - rubygems
  - certbot
  - sslopen-devel 
perlmodules:
  - Digest::MD5
  - Compress::Raw::Zlib
  - EV
  - IO::Socket::IP
  - IO::Socket::SSL
  - Mojolicious
  - Authen::OATH
  - Convert::Base32
  - File::Slurp
