yumpackages:
  - tmux
  - perl
  - cpan
  - gcc
  - git
  - nginx
  - cpanminus
  - rubygems
  - certbot
perlmodules:
  - Digest::MD5
  - Compress::Raw::Zlib
  - EV
  - IO::Socket::IP
  - IO::Socket::SSL
  - Mojolicious
  - Authen::OATH
  - Convert::Base32
  - Env
  - File::Slurp
  - File::Which
  - Mojolicious::Plugin::AccessLog
  - Toadfarm
  - HTML::TextToHTML
  - autodie
