- name: bare include main.yml
  include_vars: main.yml

- file:
    path: "~/git"
    state: directory
    group: www
    mode: u+rwx,g+r,o+r

- file:
    path: "~"
    state: directory
    mode: u+rwx,g+r,o+r

- name: install git
  git:
    repo: "{{ item.src }}"
    dest: "~/git/{{ item.name }}"
  with_items: '{{ gitrepos }}'
  tags: [git,perl]

- cron:
    name: "Set up renew SSL"
    minute: "48"
    hour: "16"
    job: "/bin/certbot renew >/dev/null"

- name: Create dir
  file:
    group: www
    owner: www
    mode:  0770
    path:  "/var/log/toadfarm/"
  become: true

- name: Create log dir
  file:
    group: www
    owner: www
    mode:  0770
    path: "/home/www/log/crontab/"
  become: true

- name: Create log dir
  file:
    group: www
    owner: www
    mode:  0750
    path: "/home/www/etc/"
  become: true