- name: bare include main.yml
  include_vars: main.yml

- file:
    path: "~/git"
    state: directory
    mode: 0755


- name: install git 
  git:
    repo: "{{ item.src }}"
    dest: "~/git/{{ item.name }}"
  with_items: '{{ gitrepos }}'
  tags: [git,perl]

- cron:
    name: "Set up renew SSL"
    minute: "48"
    hour: "16"
    job: "/bin/certbot renew >/dev/null"

- name: NGINX | ENABLE AT STARTUP
  service: name=nginx state=started enabled=yes
  become:

- name: reload toadfarm
  shell: "/home/stein/git/webserver/script/toadfarm.pl reload"
  become: www
  tags: [git,perl]
