- name: bare include main.yml
  include_vars: main.yml

- file:
    path: "~/git"
    state: directory
    mode: 0755


- name: install git 
  git:
    repo: "{{ item.src }}"
    dest: "~/git/{{ item.name }}"
  with_items: '{{ gitrepos }}'
  tags: [git,perl]
