---
#- name: bare include main.yml
#  include_vars: main.yml

- lineinfile:
    destfile: /etc/aliases
    regexp: '\w\.\w'
    line: "{{ssh_user}}: {{email_address}}"
  become: true
  tags:   email

- name: Load forward email address
  shell: newaliases
  become: true
  tags:   email

- name: service postfix restart
  service:
    name: postfix
    state: restarted
  become: true
  tags:   email

