- name: bare include main.yml
  include_vars: main.yml

- lineinfile:
    destfile: /etc/resolv.conf
    regexp: '8\.8\.8\.8'
    line: 'nameserver 8.8.8.8'
  become: true

- lineinfile:
    destfile: /etc/resolv.conf
    regexp: '8\.8\.4\.4'
    line: 'nameserver 8.8.4.4'
  become: true

- cron:
    name: "check dirs"
    minute: "40"
    hour: "0"
    job: "cd /home/stein/git/webserver && /usr/bin/git pull"

- name: upgrade all packages
  yum:
    name: '*'
    state: latest
  become: true

- name: install yum packages
  yum:
    name: epel-release
    state: latest
  become: true

- name: install yum packages2
  yum:
    name: "{{ item }}"
    state: latest
  with_items: "{{ yumpackages }}"
  become: true

- name: install perl modules
  cpanm:
    name: "{{ item }}"
  with_items: '{{ perlmodules }}'
  become: true
  tags:
    - perl

- name: Test if new config is ok
  command: "/etc/init.d/nginx configtest"
  changed_when: False
  check_mode: no
  become: yes
  become_user: root
  tags:
    - nginx

- name: Make sure web server is still running
  service: name=nginx state=started
  become: yes
  become_user: root
  tags:
    - nginx
 
