- name: bare include main.yml
  include_vars: main.yml

- lineinfile:
    destfile: /etc/resolv.conf
    regexp: '8\.8\.8\.8'
    line: 'nameserver 8.8.8.8'
  become: true

- lineinfile:
    destfile: /etc/resolv.conf
    regexp: '8\.8\.4\.4'
    line: 'nameserver 8.8.4.4'
  become: true

- cron:
    name: "check dirs nightly"
    minute: "40"
    hour: "0"
    job: "bash -l -c '/home/{{ ssh_user }}/git/utilities-perl/bin/git-status --silence' 2>/dev/null 1>/dev/null"

- cron:
    name: "nginx start at reboot"
    special_time: reboot
    job: "/sbin/ninx"
  become: true

- cron:
    name: "certbot renew"
    minute: "39"
    hour: "19"
    job: "/usr/bin/bash -l -c '/usr/bin/certbot renew'"
  become: true

- cron:
    name: "auto reload webserver"
    minute: "40"
    hour: "1"
    job: "cd /home/{{ ssh_user }}/git/webserver && /home/{{ ssh_user }}/git/perlbrew-cron/perlbrew-cron.sh script/toadfarm.pl reload >>~/log/crontab/toadfarm.log"
  become: true
  become_user: www

- cron:
    name: "auto reload guard"
    minute: "40"
    hour: "1"
    job: "cd /home/{{ ssh_user }}/git/nginx-security && /home/{{ ssh_user }}/git/perlbrew-cron/perlbrew-cron.sh bin/nginx-guard.pl reload >>~/log/crontab/nginx-guard.log"
  become: true
  become_user: www

- cron:
    name: "auto reload login"
    minute: "40"
    hour: "1"
    job: "cd /home/{{ ssh_user }}/git/nginx-security && /home/{{ ssh_user }}/git/perlbrew-cron/perlbrew-cron.sh script/login-page.pl reload >>~/log/crontab/login-page.log"
  become: true
  become_user: www


- cron:
    name: "start at reboot"
    special_time: reboot
    job: "sleep 60 && cd /home/{{ ssh_user }}/git/webserver && /home/{{ ssh_user }}/git/perlbrew-cron/perlbrew-cron.sh script/toadfarm.pl reload >>~/log/crontab/toadfarm.log"
  become: true
  become_user: www

- name: upgrade all packages
  yum:
    name: '*'
    state: latest
  become: true

- name: install yum packages
  yum:
    name: epel-release
    state: latest
  become: true

- name: install yum packages2
  yum:
    name: "{{ yumpackages }}"
    state: latest
#  with_items: "{{ yumpackages }}"
  become: true

- file:
    path: ~/git/webserver
    state: directory
    mode: 0755

- name: Set timezone
  become: true
  shell: timedatectl set-timezone Europe/Oslo

- name: Enable auto timeset
  become: true
  shell: systemctl enable ntpd

- name: Start auto timeset
  shell: systemctl start ntpd
  become: true

# secure that /etc/resolv.conf is not overwritten
- lineinfile:
    destfile: /etc/resolv.conf
    regexp: '8\.8\.8\.8'
    line: 'nameserver 8.8.8.8'
  become: true

- lineinfile:
    destfile: /etc/resolv.conf
    regexp: '8\.8\.4\.4'
    line: 'nameserver 8.8.4.4'
  become: true
