# legg til nameserver: 8.8.8.8 i /resolv.conf

- lineinfile:
    destfile: /etc/resolv.conf
    regexp: '^8\.8\.8\.8'
    line: 'nameserver: 8.8.8.8'
  become: true

- lineinfile:
    destfile: /etc/resolv.conf
    regexp: '^8\.8\.4\.4'
    line: 'nameserver: 8.8.4.4'
  become: true

- name: upgrade all packages
  yum:
    name: '*'
    state: latest
  become: true

- name: install yum packages
  yum:
    name: epel-release
    state: latest
  become: true

- name: install yum packages
  yum:
    name: "{{ item }}"
    state: latest
    with_items: "{{ yumpackages }}"
  become: true

- cpanm:
  name: "{{ item }}"
  with_items: '{{ perlmodules }}'
  become: true
