- name: bare include main.yml
  include_vars: main.yml

- name: Add two IPv4 DNS server addresses
  nmcli:
    conn_name: ens33
    type: ethernet
    ifname: ens33
    dns4:
    - 8.8.8.8
    - 8.8.4.4
    state: present
  become: true

# No auto git update. Will use manual deploy.
#- cron:
#    name: "check dirs nightly"
#    minute: "40"
#    hour: "0"
#    job: "bash -l -c '/home/{{ ssh_user }}/git/utilities-perl/bin/git-status --silence' 2>/dev/null 1>/dev/null"

- cron:
    name: "nginx start at reboot"
    special_time: reboot
    job: "/sbin/ninx  2>&1 |/home/stein/git/utilities-perl/bin/alert.pl"
  become: true

- name: upgrade all packages
  yum:
    name: '*'
    state: latest
  become: true

- name: install yum packages
  yum:
    name: epel-release
    state: latest
  become: true

- name: install yum packages2
  yum:
    name: "{{ yumpackages }}"
    state: latest
#  with_items: "{{ yumpackages }}"
  become: true

- file:
    path: ~/git/webserver
    state: directory
    mode: 0755

- name: Set timezone
  become: true
  shell: timedatectl set-timezone Europe/Oslo

- name: Enable auto timeset
  become: true
  shell: systemctl enable ntpd

- name: Start auto timeset
  shell: systemctl start ntpd
  become: true

# secure that /etc/resolv.conf is not overwritten
- lineinfile:
    destfile: /etc/resolv.conf
    regexp: '8\.8\.8\.8'
    line: 'nameserver 8.8.8.8'
  become: true

- lineinfile:
    destfile: /etc/resolv.conf
    regexp: '8\.8\.4\.4'
    line: 'nameserver 8.8.4.4'
  become: true

- file:
    path: /local
    state: directory
    mode: 0755
    owner: "{{ ssh_user }}"
    group: www
  become: true
